[profile.default]
src = "src"
out = "out"
libs = ["lib"]
metadata = true
metadata_hash = "none"  # disable ipfs
use_literal_content = true # store source code in the json file directly

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.compilers]
solc_version = "^0.8.13"

[rpc_endpoints]
Monnad_TestNet = "https://testnet-rpc.monad.xyz"
Anvil = "http://127.0.0.1:8545"
